name: "lirc_converter: Build and lint"

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build_lirc_converter.yaml"
      - "tools/apps/lirc_converter/**"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/build_lirc_converter.yaml"
      - "tools/apps/lirc_converter/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        sdk-version: ["release", "dev", "rc"]
    runs-on: ubuntu-latest
    name: 'ufbt: Build for ${{ matrix.sdk-version }} Branch'
    steps:
      - uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-version }}
          app-dir: tools/apps/lirc_converter
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "lirc_converter-${{ matrix.sdk-version }}-${{ steps.build-app.outputs.suffix }}"
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          skip-setup: true
          task: lint
          app-dir: tools/apps/lirc_converter
